### ISSUE TITLE
th colspan dont change whith column visibility

### ISSUE THREAD

**Issue by LZorglub** [DataTables/RowGroup#19]
Tested with DataTables 1.13.5 and RowGroup 1.4.0

When I change the column visibility the tr colspan dont increase/decrease automatically

It's working with DataTables 1.11.4 and RowGroup 1.1.4

**Comment by AllanJard** [comment]
Thank you! [Fixed here](https://github.com/DataTables/RowGroup/commit/297cfd3b9c8526c3ffaefb8bbdca1e36b7eab935).
