### ISSUE TITLE
Expand / collapse a group

### ISSUE THREAD

**Issue by stanleyxu2005** [DataTables/RowGroup#2]
I think it is doable. Here some sample code, I did in `startRender`

```
var hiddenStatus = {};
var tableConfig = {...}
tableConfig.startRender = function(rows, group) {
  var elem = $('<tr/>'); // Simple group header row element
  elem.on('click', function(e) {
    if (hiddenStatus[group]) {
      $(rows.nodes()).show()
    } else {
      $(rows.nodes()).hide()
    }
    hiddenStatus[group] = !hiddenStatus[group]
  });
  return elem;
};
```

I hope you can review and turn it to more high quality code. By the way, I'm thinking to show group items only by default (hide all sub-items under groups),

**Comment by DataTables** [comment]
Thank you. The problem there is that it doesn't take into account pagination in the table. That isn't going to be an easy problem to solve.

**Comment by stanleyxu2005** [comment]
Thank you. I eventually found another way to solve the problem. --> Use the child detail panel. So show summarized data (the row group headers) by default. And when click the expand button, lazy render sub rows as a table. This will fix the scroll height and pagination issue.

**Comment by kynetiv** [comment]
@stanleyxu2005 this sounds really useful. Do you happen to have an example available somewhere for how you're rendering these sub row tables?

**Comment by stanleyxu2005** [comment]
@kynetiv Assume the first column is +/- control (this column has a class `details-control`), the rest of the columns are contents.

```
const dtOptions = {} // your other table options.
dtOptions.fnInitComplete = (dom) => {
  angular.element(dom.nTBody).on('click', 'td.details-control', function() {
    const td = angular.element(this)
    const tr = td.closest('tr')
    const dtRow = table.row(this)
    if (dtRow.child.isShown()) {
      // This row is already open - close it
      dtRow.child.hide();
      tr.removeClass('shown')
      td.html(`[+]`) // show a plus icon, you can use icon button or something else
    } else {
      // Open this row
      // This is the most important part here, you should create a function and generate 
      // your content here. Sorry I just use jquery syntax
      const subRowDom = $(`<tr><td>1</td><td>2</td></tr>`) 

      dtRow.child(subRowDom).show()
      tr.addClass('shown')
      td.html(`[-]`)
    }
  })
}
```
